# Generated by Django 3.1 on 2020-08-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='file',
            new_name='sequence',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='file_path',
        ),
    ]
