# Generated by Django 3.1 on 2020-08-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200819_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='file_path',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
