# Generated by Django 3.1 on 2020-08-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sequence_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='file_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
