# Generated by Django 3.1 on 2020-08-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200820_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='sequence',
            new_name='file',
        ),
    ]
