# Generated by Django 3.1 on 2020-08-22 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200822_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='id',
        ),
        migrations.AlterField(
            model_name='sequence',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
