# Generated by Django 3.1 on 2020-08-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200822_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='dna_walk_graph_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='ratio_g_c_graph_data',
            field=models.TextField(null=True),
        ),
    ]
